#!/usr/bin/env python3

'''This script downloads candles of selected cryptocurrencies from
poloniex.com and saves them into csv files.
'''

import os
import pandas as pd
from poloniex import Poloniex

CURRENCIES = ['ETH', 'ETC', 'XMR', 'LTC']
START = 1575158400   # December 1, 2019.
END = 1575244800     # December 2, 2019.
PERIOD = 1800        # Half-hour candles.
DATA_FOLDER = 'sample_data' # Folder where to save market data.


def main():
  polo = Poloniex()
  df = pd.DataFrame()

  if not os.path.exists(DATA_FOLDER):
    os.makedirs(DATA_FOLDER)

  for currency in CURRENCIES:
    candles = polo.returnChartData(f"BTC_{currency}", PERIOD, start=START, end=END)
    df = pd.DataFrame(candles).set_index('date')
    df.to_csv(f"{DATA_FOLDER}/{currency}.csv", index_label='date')


if __name__ == '__main__':
  main()
