#!/usr/bin/env python3

import numpy as np
from exchange import Exchange

cash_amount = 1  # How much of base currency (cash) we will have.
fee = 1       # Fee in percents for each trade.
data_path = 'test_data'  # Where csv files with data are stored.

# Minimum trade volume expressed in a base currency (cash).
#min_order_size = 0.0001
min_order_size = 0

# List of currecies to use.
currencies = ['CUR1', 'CUR2']

# Create an exchange. We are at the first candle now.
ex = Exchange(cash_amount, fee, min_order_size, data_path, currencies)

#ex.balance = {'cash': 1.0, 'ETC': 0.0, 'ETH': 0.0, 'LTC': 0.0, 'XMR': 0.0}
#res = ex.make_portfolio({'cash': 0.2, 'ETC': 0.2, 'ETH': 0.2, 'LTC': 0.2, 'XMR': 0.2})
ex.make_portfolio({'cash': 0.2, 'CUR1': 0.2, 'CUR2': 0.4})
print(ex.balance)
